In [14]:
import torch
import torch.nn as nn

In [1]:
from model import CausalSelfAttention, GPTConfig

In [5]:
config = GPTConfig

In [12]:
torch.tril(torch.ones(8, 8)).view(1, 1, 8, 8)

tensor([[[[1., 0., 0., 0., 0., 0., 0., 0.],
          [1., 1., 0., 0., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0., 0.],
          [1., 1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0., 0.],
          [1., 1., 1., 1., 1., 1., 1., 0.],
          [1., 1., 1., 1., 1., 1., 1., 1.]]]])

In [13]:
torch.tril(torch.ones(config.block_size, config.block_size)).view(1, 1, config.block_size, config.block_size)

tensor([[[[1., 0., 0.,  ..., 0., 0., 0.],
          [1., 1., 0.,  ..., 0., 0., 0.],
          [1., 1., 1.,  ..., 0., 0., 0.],
          ...,
          [1., 1., 1.,  ..., 1., 0., 0.],
          [1., 1., 1.,  ..., 1., 1., 0.],
          [1., 1., 1.,  ..., 1., 1., 1.]]]])

In [32]:
x = torch.ones((1, 4, 8))

In [33]:
a = nn.Linear(8, 3 * 8, bias=False)

In [34]:
a(x)

tensor([[[ 0.3249, -1.0418, -0.0879, -0.2113,  0.8720, -0.0946,  0.8089,
          -0.7325, -0.4486,  0.5377,  0.1897, -1.1196, -0.4163, -0.4646,
           0.4444,  0.0860,  0.4843,  1.0113, -0.6168,  0.5033,  0.5977,
          -0.0941,  0.2302,  0.3485],
         [ 0.3249, -1.0418, -0.0879, -0.2113,  0.8720, -0.0946,  0.8089,
          -0.7325, -0.4486,  0.5377,  0.1897, -1.1196, -0.4163, -0.4646,
           0.4444,  0.0860,  0.4843,  1.0113, -0.6168,  0.5033,  0.5977,
          -0.0941,  0.2302,  0.3485],
         [ 0.3249, -1.0418, -0.0879, -0.2113,  0.8720, -0.0946,  0.8089,
          -0.7325, -0.4486,  0.5377,  0.1897, -1.1196, -0.4163, -0.4646,
           0.4444,  0.0860,  0.4843,  1.0113, -0.6168,  0.5033,  0.5977,
          -0.0941,  0.2302,  0.3485],
         [ 0.3249, -1.0418, -0.0879, -0.2113,  0.8720, -0.0946,  0.8089,
          -0.7325, -0.4486,  0.5377,  0.1897, -1.1196, -0.4163, -0.4646,
           0.4444,  0.0860,  0.4843,  1.0113, -0.6168,  0.5033,  0.5977,
          

In [60]:
q, k, v = a(x).split(8, dim =2)

In [61]:
q.shape

torch.Size([1, 4, 8])

In [62]:
q.transpose(1, 2).shape

torch.Size([1, 8, 4])

In [63]:
q = q.view(1, 4, 2, 8 // 2)
q.shape

torch.Size([1, 4, 2, 4])