In [14]:
import torch
import torch.nn as nn

In [1]:
from model import CausalSelfAttention, GPTConfig

In [5]:
config = GPTConfig

In [12]:
torch.tril(torch.ones(8, 8)).view(1, 1, 8, 8)

tensor([[[[1., 0., 0., 0., 0., 0., 0., 0.],
          [1., 1., 0., 0., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0., 0.],
          [1., 1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0., 0.],
          [1., 1., 1., 1., 1., 1., 1., 0.],
          [1., 1., 1., 1., 1., 1., 1., 1.]]]])

In [13]:
torch.tril(torch.ones(config.block_size, config.block_size)).view(1, 1, config.block_size, config.block_size)

tensor([[[[1., 0., 0.,  ..., 0., 0., 0.],
          [1., 1., 0.,  ..., 0., 0., 0.],
          [1., 1., 1.,  ..., 0., 0., 0.],
          ...,
          [1., 1., 1.,  ..., 1., 0., 0.],
          [1., 1., 1.,  ..., 1., 1., 0.],
          [1., 1., 1.,  ..., 1., 1., 1.]]]])

In [85]:
x = torch.ones((1, 4, 8))

In [86]:
a = nn.Linear(8, 3 * 8, bias=False)

In [87]:
a(x)

tensor([[[ 0.3027,  0.6949,  0.4734, -0.3146,  0.0827, -0.0691, -0.2610,
          -1.3717,  0.8484, -0.1178, -0.1454,  0.5303,  0.2185, -0.0925,
           0.2764, -0.1233,  0.1634,  0.9582,  0.0158, -0.5594, -1.2482,
           1.1213,  0.3296, -0.4701],
         [ 0.3027,  0.6949,  0.4734, -0.3146,  0.0827, -0.0691, -0.2610,
          -1.3717,  0.8484, -0.1178, -0.1454,  0.5303,  0.2185, -0.0925,
           0.2764, -0.1233,  0.1634,  0.9582,  0.0158, -0.5594, -1.2482,
           1.1213,  0.3296, -0.4701],
         [ 0.3027,  0.6949,  0.4734, -0.3146,  0.0827, -0.0691, -0.2610,
          -1.3717,  0.8484, -0.1178, -0.1454,  0.5303,  0.2185, -0.0925,
           0.2764, -0.1233,  0.1634,  0.9582,  0.0158, -0.5594, -1.2482,
           1.1213,  0.3296, -0.4701],
         [ 0.3027,  0.6949,  0.4734, -0.3146,  0.0827, -0.0691, -0.2610,
          -1.3717,  0.8484, -0.1178, -0.1454,  0.5303,  0.2185, -0.0925,
           0.2764, -0.1233,  0.1634,  0.9582,  0.0158, -0.5594, -1.2482,
          

In [88]:
q, k, v = a(x).split(8, dim =2)
q.shape

torch.Size([1, 4, 8])

In [89]:
q = q.view(1, 4, 2, 8 // 2)
q.shape

torch.Size([1, 4, 2, 4])

In [90]:
q = q.transpose(1, 2)
q.shape

torch.Size([1, 2, 4, 4])

In [91]:
import math
att = (q @ q.transpose(-2, -1)) * (1.0 / math.sqrt(q.shape[-1]))
att.shape

torch.Size([1, 2, 4, 4])